export const storeProducts = [
  {
    id: 1,
    title: "Микрозелень Подсолнух",
    group: 'micro',
    img: "img/micro/micro_podsolnuh.png",
    price: 99,
    weight: "100 г.",
    properties:[
      {id: 1,
      title: 'Белки',
      value: '2,4 г.'},
      {id: 2,
      title: 'Жиры',
      value: '4,7 г.'},
      {id: 3,
      title: 'Углеводы',
      value: '2,4 г.'},
      {id: 4,
      title: 'Энергетическая ценность',
      value: '53 ккал.'},
      {id: 5,
      title: 'Условия хранения',
      value: 'в холодильнике'}
      ],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 2,
    title: "Микрозелень Горох",
    group: 'micro',
    img: "img/micro/micro_goroh.png",
    price: 99,
    weight: "100 г.",
    properties:[
      {id: 1,
      title: 'Белки',
      value: '4,8 г.'},
      {id: 2,
      title: 'Жиры',
      value: '0,5 г.'},
      {id: 3,
      title: 'Углеводы',
      value: '4,3 г.'},
      {id: 4,
      title: 'Энергетическая ценность',
      value: '31 ккал.'},
      {id: 5,
      title: 'Условия хранения',
      value: 'в холодильнике'}
      ],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 3,
    title: "Микрозелень Редис",
    group: 'micro',
    img: "img/micro/micro_redis.png",
    price: 149,
    weight: "100 г.",
    properties:[
      {id: 1,
      title: 'Белки',
      value: '3,8 г.'},
      {id: 2,
      title: 'Жиры',
      value: '2,5 г.'},
      {id: 3,
      title: 'Углеводы',
      value: '3,6 г.'},
      {id: 4,
      title: 'Энергетическая ценность',
      value: '43 ккал.'},
      {id: 5,
      title: 'Условия хранения',
      value: 'в холодильнике'}
      ],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 4,
    title: "Томаты Сортовые",
    group: 'vegs',
    img: "img/vegs/tomato.jpg",
    price: 133,
    weight: "1 кг.",
    properties:[
      {id: 1,
      title: 'Белки',
      value: '0,6 г.'},
      {id: 2,
      title: 'Жиры',
      value: '0,2 г.'},
      {id: 3,
      title: 'Углеводы',
      value: '4,2 г.'},
      {id: 4,
      title: 'Энергетическая ценность',
      value: '20 ккал.'},
      {id: 5,
      title: 'Условия хранения',
      value: 'в холодильнике'}
      ],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 5,
    title: "Салат Старфайтер",
    group: 'vegs',
    img: "img/vegs/salad.jpg",
    price: 53,
    weight: "200 г.",
    properties:[
      {id: 1,
      title: 'Белки',
      value: '1,5 г.'},
      {id: 2,
      title: 'Жиры',
      value: '0,2 г.'},
      {id: 3,
      title: 'Углеводы',
      value: '2,3 г.'},
      {id: 4,
      title: 'Энергетическая ценность',
      value: '17 ккал.'},
      {id: 5,
      title: 'Условия хранения',
      value: 'в холодильнике'}
      ],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 6,
    title: "Базилик Фиолетовый",
    group: 'vegs',
    img: "img/vegs/basil.jpg",
    price: 59,
    weight: "100 г.",
    properties:[
      {id: 1,
      title: 'Белки',
      value: '2,56 г.'},
      {id: 2,
      title: 'Жиры',
      value: '0,61 г.'},
      {id: 3,
      title: 'Углеводы',
      value: '4,34 г.'},
      {id: 4,
      title: 'Энергетическая ценность',
      value: '27 ккал.'},
      {id: 5,
      title: 'Условия хранения',
      value: 'в холодильнике'}
      ],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 7,
    title: "Редис Донар",
    group: 'vegs',
    img: "img/vegs/redis.jpg",
    price: 33,
    weight: "250 г.",
    properties:[
      {id: 1,
      title: 'Белки',
      value: '0,6 г.'},
      {id: 2,
      title: 'Жиры',
      value: '0,2 г.'},
      {id: 3,
      title: 'Углеводы',
      value: '4,2 г.'},
      {id: 4,
      title: 'Энергетическая ценность',
      value: '14 ккал.'},
      {id: 5,
      title: 'Условия хранения',
      value: 'в холодильнике'}
      ],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 8,
    title: "Вешенки",
    group: 'vegs',
    img: "img/vegs/mushroom.jpg",
    price: 87,
    weight: "400 г.",
    properties:[
      {id: 1,
      title: 'Белки',
      value: '3,3 г.'},
      {id: 2,
      title: 'Жиры',
      value: '0,5 г.'},
      {id: 3,
      title: 'Углеводы',
      value: '6,5 г.'},
      {id: 4,
      title: 'Энергетическая ценность',
      value: '43 ккал.'},
      {id: 5,
      title: 'Условия хранения',
      value: 'в холодильнике'}
      ],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 9,
    title: "Огурец сортовой",
    group: 'vegs',
    img: "img/vegs/ogurec.jpg",
    price: 109,
    weight: "1 кг.",
    properties:[
      {id: 1,
      title: 'Белки',
      value: '0,8 г.'},
      {id: 2,
      title: 'Жиры',
      value: '0,1 г.'},
      {id: 3,
      title: 'Углеводы',
      value: '2,8 г.'},
      {id: 4,
      title: 'Энергетическая ценность',
      value: '15 ккал.'},
      {id: 5,
      title: 'Условия хранения',
      value: 'в холодильнике'}
      ],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 10,
    title: "Томат Тореро",
    group: 'vegs',
    img: "img/vegs/tomato_standart.jpg",
    price: 119,
    weight: "1 кг.",
    properties:[
      {id: 1,
      title: 'Белки',
      value: '0,7 г.'},
      {id: 2,
      title: 'Жиры',
      value: '0,15 г.'},
      {id: 3,
      title: 'Углеводы',
      value: '4,2 г.'},
      {id: 4,
      title: 'Энергетическая ценность',
      value: '22 ккал.'},
      {id: 5,
      title: 'Условия хранения',
      value: 'в холодильнике'}
      ],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 11,
    title: "Огурец Мева",
    group: 'vegs',
    img: "img/vegs/ogurec_meva.jpg",
    price: 79,
    weight: "1 кг.",
    properties:[
      {id: 1,
      title: 'Белки',
      value: '0,6 г.'},
      {id: 2,
      title: 'Жиры',
      value: '0,15 г.'},
      {id: 3,
      title: 'Углеводы',
      value: '3 г.'},
      {id: 4,
      title: 'Энергетическая ценность',
      value: '18 ккал.'},
      {id: 5,
      title: 'Условия хранения',
      value: 'в холодильнике'}
      ],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 12,
    title: "Набор Горох",
    group: 'nabor',
    img: "img/nabor/nabor_goroh.png",
    price: 279,
    weight: "530 г.",
    properties:[
      {id: 1,
      title: 'Срок выращивания',
      value: '10-12 дней'},
      {id: 2,
      title: 'Комплектация',
      value: 'Пластиковый контейнер, семена гороха, грунт, упаковка'},
      {id: 3,
      title: 'Условия хранения',
      value: 'в холодильнике'}
      ],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 13,
    title: "Набор Редис",
    group: 'nabor',
    img: "img/nabor/nabor_redis.png",
    price: 279,
    weight: "530 г.",
    properties:[
      {id: 1,
      title: 'Срок выращивания',
      value: '10-12 дней'},
      {id: 2,
      title: 'Комплектация',
      value: 'Пластиковый контейнер, семена редиса, грунт, упаковка'},
      {id: 3,
      title: 'Условия хранения',
      value: 'в холодильнике'}
      ],
    inCart: false,
    count: 0,
    total: 0
  },
  {
    id: 14,
    title: "Набор Подсолнечник",
    group: 'nabor',
    img: "img/nabor/nabor_pods.png",
    price: 279,
    weight: "530 г.",
    properties:[
      {id: 1,
      title: 'Срок выращивания',
      value: '10-12 дней'},
      {id: 2,
      title: 'Комплектация',
      value: 'Пластиковый контейнер, семена подсолнечника, грунт, упаковка'},
      {id: 3,
      title: 'Условия хранения',
      value: 'в холодильнике'}
      ],
    inCart: false,
    count: 0,
    total: 0
  }
];

export const detailProduct = {
  detailedProduct: {
  id: 1,
  title: "Микрозелень Подсолнух",
  group: 'micro',
  img: "img/micro/micro_podsolnuh.png",
  price: 99,
  weight: "100 г.",
  properties:[
    {id: 1,
    title: 'Белки',
    value: '2,4 г.'},
    {id: 2,
    title: 'Жиры',
    value: '4,7 г.'},
    {id: 3,
    title: 'Углеводы',
    value: '2,4 г.'},
    {id: 4,
    title: 'Энергетическая ценность',
    value: '53 ккал.'},
    {id: 5,
    title: 'Условия хранения',
    value: 'в холодильнике'}
    ],
  inCart: false,
  count: 0,
  total: 0
  }
}

export let cartProducts = [

]
